// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnionStarAPI.Data;

namespace UnionStarAPI.Migrations
{
    [DbContext(typeof(UnionStarContext))]
    [Migration("20220718033115_AgregarCotizaciones")]
    partial class AgregarCotizaciones
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UnionStarAPI.Models.Cotizacion", b =>
                {
                    b.Property<string>("IdCotizacion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Concepto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondicionesEntrega")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaDireccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaTitulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdInteresado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdObjeto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdPersonal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdServicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Importe")
                        .HasColumnType("float");

                    b.Property<string>("ModoPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlazoEntrega")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCotizacion");

                    b.ToTable("Cotizacion");
                });

            modelBuilder.Entity("UnionStarAPI.Models.Cotizaciones", b =>
                {
                    b.Property<string>("IdCotizacion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondicionesEntrega")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaDireccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaTitulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdInteresado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdObjeto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdPersonal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdServicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Importe")
                        .HasColumnType("float");

                    b.Property<string>("ModoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlazoEntrega")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCotizacion");

                    b.ToTable("Cotizaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
